AWSTemplateFormatVersion: '2010-09-09'
Description: Parameters stack for ASG stack
# Create with 
# aws cloudformation create-stack --template-body file://cfn/40_asg_parameters/params_infra.yml  --stack-name ASGParameters --parameters ParameterKey=KeyName,ParameterValue=tpe-ed25519 ParameterKey=SecurityGroups,ParameterValue=sg-01e6e524fed71df26 ParameterKey=Subnets,ParameterValue=subnet-918fc1fb\\,subnet-efaa2f93
# Update with
# aws cloudformation update-stack --template-body file://cfn/40_asg_parameters/params_infra.yml  --stack-name ASGParameters --parameters ParameterKey=KeyName,ParameterValue=tpe-ed25519 ParameterKey=SecurityGroups,ParameterValue=sg-01e6e524fed71df26 ParameterKey=Subnets,ParameterValue=subnet-918fc1fb\\,subnet-efaa2f93
Parameters:
  Namespace:
    Description: Environment. Used to identify various things as they are created
    Type: String
    Default: Development
  KeyName:
    Description: Keypair for EC2 acccess
    Type: String
  InstanceType:
    Description: Amazon EC2 instance type for the instances
    Type: String
    AllowedValues:
      - t4g.micro
      - t4g.small
      - t4g.medium
    Default: t4g.micro
  SecurityGroups:
    Description: The security group to use
    Type: String
    #List<AWS::EC2::SecurityGroup::Id>
    ConstraintDescription: Must be valid security group(s)
  Subnets:
    Type: String
    #'List<AWS::EC2::Subnet::Id>'
    Description: A list of subnets for the Auto Scaling group
Resources:
  Ec2KeyName:
    Type: "AWS::SSM::Parameter"
    Properties:
      Description: "Key-pair for EC2 access"
      Name: !Sub "/${Namespace}/KeyPair"
      Type: String
      Value: !Ref KeyName
      AllowedPattern: "^[a-zA-Z][-a-zA-Z0-9]*"
  InstanceTypeParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Description: "Instance type for the asg"
      Name: !Sub "/${Namespace}/InstanceType"
      Type: String
      Value: !Ref InstanceType
      # AllowedPattern: "^[a-zA-Z][-a-zA-Z0-9]*"
  SecurityGroupsParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Description: "Security groups"
      Name: !Sub "/${Namespace}/SecurityGroups"
      Type: String
      Value: !Ref SecurityGroups
  SubnetsParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Description: "Subnets to place instance in"
      Name: !Sub "/${Namespace}/Subnets"
      Type: String
      Value: !Ref Subnets
