AWSTemplateFormatVersion: '2010-09-09'
Description: Parameters stack for ASG stack
Parameters:
  Namespace:
    Description: Environment. Used to identify various things as they are created
    Type: String
    Default: Development
    AllowedPattern: "^[a-zA-Z][a-zA-Z0-9]*$"
    ConstraintDescription: Letters and numbers only
  KeyName:
    Description: Keypair for EC2 acccess
    Type: String
  InstanceType:
    Description: Amazon EC2 instance type for the instances
    Type: String
    AllowedValues:
      - t4g.micro
      - t4g.small
      - t4g.medium
    Default: t4g.micro
  SecurityGroups:
    Description: The security group to use. Only one group. Would work with multiple groups if we didn't have a dynamic ssm parameter name
    Type: "List<AWS::EC2::SecurityGroup::Id>"
    ConstraintDescription: Must be valid security group(s)
  Vpc:
    Type: "AWS::EC2::VPC::Id"
    Description: VPC to place things in
  Subnets:
    Type: "List<AWS::EC2::Subnet::Id>"
    Description: A list of subnets for the Auto Scaling group
  DeployZipBucket:
    Type: String
    Description: Bucket with application to deploy. Must be a versioned bucket
    AllowedPattern: "^[a-z0-9]+[a-z0-9-]{1,61}[a-z0-9]+$"
  DeployZipKey:
    Type: String
    Description: S3 key of deploy zip.
    AllowedPattern: "^[a-zA-Z0-9]+.*$"
    ConstraintDescription: No leading slash. And no other specials as first char
  CloudTrailPrefix:
    Type: String
    Description: S3 prefix for cloudtrail logs (for S3 trigger)
    AllowedPattern: "^[a-zA-Z0-9]+.*[a-zA-Z0-9]$"
    ConstraintDescription: No leading slash or ending slash.
Resources:
  KeyNameParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Description: "Key-pair for EC2 access"
      Name: !Sub "/${Namespace}/KeyName"
      Type: String
      Value: !Ref KeyName
      AllowedPattern: "^[a-zA-Z][-a-zA-Z0-9]*"
  InstanceTypeParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Description: "Instance type for the asg"
      Name: !Sub "/${Namespace}/InstanceType"
      Type: String
      Value: !Ref InstanceType
      # AllowedPattern: "^[a-zA-Z][-a-zA-Z0-9]*"
  SecurityGroupsParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Description: "Security groups"
      Name: !Sub "/${Namespace}/SecurityGroups"
      Type: StringList
      Value: !Join [",", !Ref SecurityGroups]
      AllowedPattern: "^sg-[a-f0-9]{8,}$"
  VpcParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Description: "VPC for security groups"
      Name: !Sub "/${Namespace}/Vpc"
      Type: StringList
      Value: !Ref Vpc
      AllowedPattern: "^vpc-[a-f0-9]{8,}$"
  SubnetsParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Description: "Subnets to place instances in. VPCZoneIdentifier seems to be tolerant and resolves the list correctly"
      Name: !Sub "/${Namespace}/Subnets"
      Type: StringList
      Value: !Join [",", !Ref Subnets]
      AllowedPattern: "^subnet-[a-f0-9]{8,}$"
  DeployZipBucketParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Description: "Deploy Zip S3 bucket"
      Name: !Sub "/${Namespace}/DeployZipBucket"
      Type: String
      Value: !Ref DeployZipBucket
  DeployZipKeyParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Description: "Deploy Zip Object key"
      Name: !Sub "/${Namespace}/DeployZipKey"
      Type: String
      Value: !Ref DeployZipKey
  CloudTrailPrefixParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Description: "CloudTrail Prefix"
      Name: !Sub "/${Namespace}/CloudTrailPrefix"
      Type: String
      Value: !Ref CloudTrailPrefix
  CloudWatchAgentConfig:
    Type: "AWS::SSM::Parameter"
    Properties:
      Description: "CloudWatch agent config json (linux version)"
      Name: !Sub "/${Namespace}/AmazonCloudWatch-linux"
      Type: String
      # Need to go with root user in order to read the logs
      Value: !Sub |
        {
          "agent": {
            "run_as_user": "root"
          },
          "logs": {
            "logs_collected": {
              "files": {
                "collect_list": [
                  {
                    "file_path": "/var/log/messages",
                    "log_group_name": "/${Namespace}/var/log/messages",
                    "log_stream_name": "{instance_id}",
                    "retention_in_days": 60
                  },
                  {
                    "file_path": "/var/log/secure",
                    "log_group_name": "/${Namespace}/var/log/secure",
                    "log_stream_name": "{instance_id}",
                    "retention_in_days": 60
                  },
                  {
                    "file_path": "/var/log/cron",
                    "log_group_name": "/${Namespace}/var/log/cron",
                    "log_stream_name": "{instance_id}",
                    "retention_in_days": 60
                  },
                  {
                    "file_path": "/var/log/yum.log",
                    "log_group_name": "/${Namespace}/var/log/yum.log",
                    "log_stream_name": "{instance_id}",
                    "retention_in_days": 60
                  },
                  {
                    "file_path": "/opt/codedeploy-agent/deployment-root/deployment-logs/codedeploy-agent-deployments.log",
                    "log_group_name": "/${Namespace}/codedeploy/logs",
                    "log_stream_name": "{instance_id}",
                    "retention_in_days": 60
                  }
                ]
              }
            }
          },
          "metrics": {
            "append_dimensions": {
              "AutoScalingGroupName": "${!aws:AutoScalingGroupName}",
              "ImageId": "${!aws:ImageId}",
              "InstanceId": "${!aws:InstanceId}",
              "InstanceType": "${!aws:InstanceType}"
            },
            "metrics_collected": {
              "statsd": {
                "metrics_aggregation_interval": 60,
                "metrics_collection_interval": 60,
                "service_address": ":8125"
              }
            }
          }
        }

