AWSTemplateFormatVersion: '2010-09-09'
Description: Deployment parts of stack.
Parameters:
  Namespace:
    Description: Environment. Used to identify various things as they are created
    Type: String
    Default: Development
Resources:
  CodeDeployServiceIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: CodeDeployTrustPolicy
          Effect: Allow
          Principal:
            Service:
            - codedeploy.amazonaws.com
          Action: sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSCodeDeployRole
  CdApplication:
    Type: AWS::CodeDeploy::Application
  CdDeployConfig:
    Type: AWS::CodeDeploy::DeploymentConfig
    Properties:
      ComputePlatform: Server
      MinimumHealthyHosts:
        Value: 0
        Type: "HOST_COUNT"
      # TrafficRoutingConfig:
      #   Type: AllAtOnce
  CdDeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties:
      ApplicationName: !Ref CdApplication
      AutoScalingGroups: 
        - "Fn::ImportValue": !Sub  "ArmAsg:${Namespace}:ScalingGroupName"
      LoadBalancerInfo:
        # The tortured whitespace is intentional. Well-formed YAML can't have two mappings on a single line
        TargetGroupInfoList:
          - Name: 
              "Fn::ImportValue": !Sub "ArmAsg:${Namespace}:TargetGroupName"
      DeploymentStyle:
        DeploymentType: IN_PLACE
        DeploymentOption: WITH_TRAFFIC_CONTROL
      Deployment:
        Description: Initial deployment
        IgnoreApplicationStopFailures: 'true'
        Revision:
          RevisionType: S3
          S3Location:
            Bucket: !Sub "{{resolve:ssm:/${Namespace}/DeployZipBucket}}"
            Key: !Sub "{{resolve:ssm:/${Namespace}/DeployZipKey}}"
            BundleType: Zip
      ServiceRoleArn: !GetAtt CodeDeployServiceIAMRole.Arn
